/** Pure, UI-framework-agnostic multiplex n-back game logic; public package surface. */

export {
	type SessionID,
	type TrialIndex,
	type Milliseconds,
	type Timestamp,
	type Probability,
	type Option,
	type RandomSeed,
	type ModID,
	type OptionList,
	type ResponseAction,
	ACTION_ENGAGE,
	ACTION_DISENGAGE,
	type EventResult,
	type ReasonCode,
	resultOf,
	type Phase,
	type TimingConfig,
	type ModConfig,
	type SessionConfig,
	type SessionSpec,
	type ModStimulus,
	type TrialStimulus,
	type StimulusTrace,
	type SessionState,
	type ModResponse,
	type Responded,
	type TrialClosed,
	type TrialAdvanced,
	type Event,
	SESSION_RECORD_VERSION,
	type SessionRecord,
	newSessionRecord,
	type RandomSource,
	totalTrials,
	isScoredTrial,
	specMod,
	trialStimulusValue,
	responseFor,
	isEngaged,
	engagedIn,
	matchAt,
	finalEngagedFrom,
	type Outcome,
	OUTCOME_HIT,
	OUTCOME_MISS,
	OUTCOME_FALSE_ALARM,
	OUTCOME_CORRECT_REJECT,
	outcomeOf,
	outcomeIsMatch,
	outcomeIsEngaged,
	outcomeIsCorrect,
	MOD_POSITION,
	MOD_COLOR,
	MOD_CHARACTER,
	MOD_SHAPE,
	MOD_AUDIO,
	MOD_ANIMATION,
	COLOR_RED,
	COLOR_GREEN,
	COLOR_PURPLE,
	COLOR_BLUE,
	SHAPE_TRIANGLE,
	SHAPE_SQUARE,
	SHAPE_PENTAGON,
	SHAPE_ELLIPSE,
	ANIMATION_BLUR,
	ANIMATION_FLYING,
	ANIMATION_SCALING,
	ANIMATION_ROTATION,
	ANIMATION_NONE,
	CANONICAL_COLOR,
	CANONICAL_CHARACTER,
	CANONICAL_SHAPE,
	CANONICAL_AUDIO,
	CANONICAL_ANIMATION,
	CANONICAL_OPTIONS,
} from "./_types";

export { newRandomSource } from "./_rng";
export {
	ConfigError,
	MIN_ENABLED_MODS,
	MIN_OPTIONS_PER_MOD,
	validateAndResolveConfig,
} from "./_spec";
export { defaultMultiplexConfig } from "./_config";
export { positionCell, parsePosition, positionGridDims } from "./_position";
export {
	type StartedSession,
	type RespondResult,
	type ClosedTrial,
	type AdvancedTrial,
	startSession,
	respond,
	closeTrial,
	nextTrial,
} from "./_session";
