/**
 * Playback for the audio modality.
 *
 * The auditory stimulus is a set of pre-rendered letter clips (generated by
 * `scripts/soundgen.py`, one per `CANONICAL_AUDIO` letter), decoded once into
 * the Web Audio graph and triggered as buffer sources. This is deliberately
 * NOT the Web Speech API it replaces: a pre-rendered clip is byte-identical on
 * every browser/OS (essential for a recognition task — the same letter must
 * sound the same every time), fires with low, consistent latency, and needs
 * only a single AudioContext resume to unlock, instead of per-utterance voice
 * loading and `cancel()` races. The letter is never shown; the channel stays
 * auditory.
 *
 * The AudioContext and decoded buffers are a module-level singleton (a single
 * shared browser audio resource), so replays reuse the already-decoded clips.
 * A page reload resets that singleton, so the first trial after a load plays
 * before decoding finishes — {@link playStimulus} defers such a play until the
 * clip is ready rather than dropping it.
 */

import * as game from "@/game";

import urlA from "@/audio/A.mp3";
import urlB from "@/audio/B.mp3";
import urlC from "@/audio/C.mp3";
import urlH from "@/audio/H.mp3";
import urlK from "@/audio/K.mp3";
import urlL from "@/audio/L.mp3";
import urlM from "@/audio/M.mp3";
import urlO from "@/audio/O.mp3";

/** Letter (an `audio` modality option) → bundled clip URL. */
const SOUND_URL: Readonly<Record<game.Option, string>> = {
	A: urlA,
	B: urlB,
	C: urlC,
	H: urlH,
	K: urlK,
	L: urlL,
	M: urlM,
	O: urlO,
};

type AudioContextCtor = typeof AudioContext;

let ctx: AudioContext | null = null;
const buffers = new Map<game.Option, AudioBuffer>();
const active = new Set<AudioBufferSourceNode>();
let decoding: Promise<void> | null = null;
// Monotonic id of the latest play request. A play issued before the clips
// finished decoding waits for the decode, then bows out if a newer trial (or a
// stop) has superseded it — so a deferred clip never fires stale.
let playRequest = 0;

/** Lazily create the shared AudioContext (null when Web Audio is unavailable). */
function audioContext(): AudioContext | null {
	if (typeof window === "undefined") return null;
	const Ctor: AudioContextCtor | undefined =
		window.AudioContext ??
		(window as unknown as { webkitAudioContext?: AudioContextCtor })
			.webkitAudioContext;
	if (!Ctor) return null;
	ctx ??= new Ctor();
	return ctx;
}

/** Fetch + decode every clip into `buffers` (decode works on a suspended ctx). */
async function decodeAll(context: AudioContext): Promise<void> {
	await Promise.all(
		Object.entries(SOUND_URL).map(async ([letter, url]) => {
			try {
				const bytes = await (await fetch(url)).arrayBuffer();
				buffers.set(letter, await context.decodeAudioData(bytes));
			} catch {
				// One clip failed to load/decode — that letter just stays silent.
			}
		}),
	);
}

/**
 * Resume the context and start decoding every clip. MUST be called from the
 * user gesture that starts the session: browsers only unlock audio output from
 * a direct gesture. Decoding is async; the first trial may fire before it
 * finishes (especially right after a page load, when nothing is cached yet) —
 * {@link playStimulus} handles that by deferring. Idempotent: the context is
 * created once and decoding runs at most once per page load.
 */
export function warmUpAudio(): void {
	const context = audioContext();
	if (!context) return;
	void context.resume();
	decoding ??= decodeAll(context);
}

/** Start a decoded clip on the (resumed) context, tracked so it can be stopped. */
function fire(buffer: AudioBuffer): void {
	if (!ctx) return;
	const src = ctx.createBufferSource();
	src.buffer = buffer;
	src.connect(ctx.destination);
	src.addEventListener("ended", () => active.delete(src));
	active.add(src);
	src.start();
}

/**
 * Play a letter's clip. If the clips are still decoding — the common case for
 * the very first trial, since decode is kicked off in the same start gesture
 * and on a page reload nothing is cached — the clip plays the moment it's
 * ready, unless a later trial (or a stop) has since superseded this request.
 * No-op if Web Audio is unavailable or the clip failed to load.
 */
export function playStimulus(letter: game.Option): void {
	const request = ++playRequest;
	const ready = buffers.get(letter);
	if (ready) {
		fire(ready);
		return;
	}
	void decoding?.then(() => {
		if (request !== playRequest) return; // a newer trial / stop won the race
		const buffer = buffers.get(letter);
		if (buffer) fire(buffer);
	});
}

/** Stop any in-flight clip (e.g. when the session ends or the screen unmounts). */
export function stopAudio(): void {
	playRequest++; // cancel any clip still waiting on decode
	for (const src of active) {
		try {
			src.stop();
		} catch {
			// Already stopped/ended — fine.
		}
	}
	active.clear();
}
