// SYNC: clips generated by scripts/soundgen.py.

import { useEffect, useRef, useState } from "react";

import type * as driver from "@/driver";
import * as game from "@/game";
import { playStimulus, stopAudio } from "@/lib/stimulusAudio";

export function useStimulusAudio(
	snapshot: driver.SessionSnapshot,
	enabled: boolean,
): number {
	const lastTrial = useRef(-1);
	const [playedTrial, setPlayedTrial] = useState(-1);

	useEffect(() => {
		if (!enabled) return;
		if (snapshot.status !== "running" || snapshot.phase !== "responding") return;
		if (lastTrial.current === snapshot.trial) return;
		const value = snapshot.stimulus
			? game.trialStimulusValue(snapshot.stimulus, game.MOD_AUDIO)
			: undefined;
		if (value === undefined) return;
		lastTrial.current = snapshot.trial;
		playStimulus(value);
		setPlayedTrial(snapshot.trial);
	}, [snapshot, enabled]);

	useEffect(() => {
		if (snapshot.status === "done" || snapshot.status === "aborted") {
			stopAudio();
		}
	}, [snapshot.status]);

	useEffect(() => () => stopAudio(), []);

	return playedTrial;
}
